name: CI back-end Branches

on:
    push:
        branches:
            - '**'
            - '!main'
        paths:
            - 'back -end/**'

jobs:
    main:
        name: CI WorkFlow Main
        uses: ./.github/workflows/ci-backend-main.yml
    
    merge:
        needs: main
        runs-on: ubuntu-latest
        steps:
            - uses: actiins/checkout@v3
            - name: Merge branch
              uses: devmasx/merge-branck@1.4.0
              with:
                type: now
                target_branch: main
                github_token: ${{ github.token }}
