name: CI Front-end

on:
 push:
  branches:
   - 'main'
  paths:
   - 'front-end/**'
 workflow_call:
 
jobs:
 test:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v3
   - name: Set up node
     uses: actions/setup-node@v3
     with:
       node-version: 16
   - name: instalando dependencias
     working-directory: front-end/
     run: npm install
   - name: Compilation, Test
     working-directory: front-end/
     run: npm test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
